---
title: "Experiment 1"ed
author: "Anna Jenul et al."
date: "August 2023"
output:
  html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

load(file = "../data/preprocessing.Rdata")
```

```{r packages}
library(UBayFS)
```

```{r matrix initializations}
# options for maximum number of features (max_s)
max_s_opts = c(5, 10, 20, 30, 40)
nfolds = 5 # number of folds
```

```{r feature selection}
# train UBayFS models to obtain features
feature_df <- c()
for (max_s in max_s_opts) {
  set.seed(1)
  for (test_fold in 1:nfolds) {
    # build model
    model = build.UBaymodel(data_list[[test_fold]]$train_data,
                          target = as.numeric(data_list[[test_fold]]$train_target$category), 
                          M = 100,
                          tt_split = 0.75, 
                          nf = max_s, 
                          method = "mRMR",
                          prior_model ="dirichlet",
                          weights = weights,
                          lam = 10,
                          constraints = buildConstraints(constraint_types = c("max_size"),
                                              constraint_vars = max_s,
                                              num_elements = ncol(data_list[[test_fold]]$train_data),
                                              rho = Inf),
                          optim_method = "GA",
                          popsize = 100,
                          maxiter = 100,
                          shiny = FALSE
    )
  
    # train model
    model = train(model)

    # extract features
    features = which(model$output$feature_set[1,] == 1)
    feature_df <- rbind(feature_df, data.frame(index = features, 
                                               max_s = max_s, 
                                               fold = test_fold))
  }
}

# save to Rdata file
write.csv(feature_df, file = "UBayFS_features_exp1.csv", row.names = FALSE)
```

